spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/foo_erp?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root
    rules:
      sharding:
        tables:
          users:
            actual-data-nodes: ds0.users_$->{0..1}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: users_inline
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
          users_roles:
            actual-data-nodes: ds0.users_roles_$->{0..1}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: users_roles_inline
        binding-tables:
          - users,users_roles
        broadcast-tables:
          - role
        sharding-algorithms:
          users_inline:
            type: INLINE
            props:
              algorithm-expression: users_$->{id % 2}
          users_roles_inline:
            type: INLINE
            props:
              algorithm-expression: users_roles_$->{user_id % 2}
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true 